--- include/uapi/linux/Kbuild
+++ include/uapi/linux/Kbuild
@@ -56,6 +56,7 @@
 header-y += atmsap.h
 header-y += atmsvc.h
 header-y += audit.h
+header-y += aufs_type.h
 header-y += auto_fs.h
 header-y += auto_fs4.h
 header-y += auxvec.h
